package com.d201.fundingift.unit.mock;


import com.d201.fundingift.funding.domain.Funding;
import com.d201.fundingift.funding.domain.port.FundingRepository;
import com.d201.fundingift.funding.intrastructure.entity.FundingEntity;
import org.springframework.data.domain.Pageable;
import org.springframework.data.domain.Slice;

import java.time.LocalDateTime;
import java.util.ArrayList;
import java.util.List;
import java.util.Objects;
import java.util.Optional;

public class FakeFundingRepository implements FundingRepository {

    private Long autoGeneratedId = 0L;
    private final List<Funding> data = new ArrayList<>();

    @Override
    public void save(Funding funding) {
        if(funding.getId() == null) {
            Funding newFunding = Funding.builder()
                    .id(++autoGeneratedId)
                    .sumPrice(funding.getSumPrice())
                    .minPrice(funding.getMinPrice())
                    .targetPrice(funding.getTargetPrice())
                    .anniversaryDate(funding.getAnniversaryDate())
                    .startDate(funding.getStartDate())
                    .endDate(funding.getEndDate())
                    .title(funding.getTitle())
                    .content(funding.getContent())
                    .accountBank(funding.getAccountBank())
                    .accountNo(funding.getAccountNo())
                    .name(funding.getName())
                    .phoneNumber(funding.getPhoneNumber())
                    .defaultAddr(funding.getDefaultAddr())
                    .detailAddr(funding.getDetailAddr())
                    .zipCode(funding.getZipCode())
                    .fundingStatus(funding.getFundingStatus())
                    .isPrivate(funding.getIsPrivate())
                    .consumer(funding.getConsumer())
                    .anniversaryCategory(funding.getAnniversaryCategory())
                    .product(funding.getProduct())
                    .productOption(funding.getProductOption())
                    .createdAt(LocalDateTime.now())
                    .updatedAt(LocalDateTime.now())
                    .deletedAt(null)
                    .build();

            data.add(newFunding);
        } else {
            data.removeIf(item -> Objects.equals(item.getId(), funding.getId()));
            data.add(funding);
        }
    }

    @Override
    public Optional<Funding> findById(long id) {
        return data.stream().filter(item -> item.getId().equals(id)).findAny();
    }

    @Override
    public Slice<FundingEntity> findAllFriendsFunding(Long consumerId, Pageable pageable) {
        return null;
    }

}
