package com.d201.fundingift.unit.mock;

import com.d201.fundingift.product.entity.Product;
import com.d201.fundingift.product.repository.ProductRepository;
import org.springframework.data.domain.*;
import org.springframework.data.repository.query.FluentQuery;

import java.util.ArrayList;
import java.util.List;
import java.util.Objects;
import java.util.Optional;
import java.util.function.Function;

public class FakeProductRepository implements ProductRepository {

    private Long autoGeneratedId = 0L;
    private final List<Product> data = new ArrayList<>();
    @Override
    public Optional<Product> findById(Long id) {
        return data.stream().filter(item -> item.getId().equals(id)).findAny();
    }

    @Override
    public <S extends Product> S save(S entity) {

        if(entity.getId() == null) {
            Product newProduct = Product.builder()
                    .id(++autoGeneratedId)
                    .name(entity.getName())
                    .price(entity.getPrice())
                    .description(entity.getDescription())
                    .image(entity.getImage())
                    .reviewAvg(entity.getReviewAvg())
                    .reviewCnt(entity.getReviewCnt())
                    .status(entity.getStatus())
                    .build();

            data.add(newProduct);

            return (S) newProduct;
        } else {
            data.removeIf(item -> Objects.equals(item.getId(), entity.getId()));
            data.add(entity);

            return entity;
        }
    }

    @Override
    public boolean existsById(Long aLong) {
        return false;
    }

    @Override
    public Slice<Product> findAllSliceByCategoryIdAndKeyword(Integer productCategoryId, String keyword, Pageable pageable) {
        return null;
    }

    @Override
    public Slice<Product> findAllSliceOrderByFundingCount(Pageable pageable) {
        return null;
    }

    @Override
    public void flush() {

    }

    @Override
    public <S extends Product> S saveAndFlush(S entity) {
        return null;
    }

    @Override
    public <S extends Product> List<S> saveAllAndFlush(Iterable<S> entities) {
        return null;
    }

    @Override
    public void deleteAllInBatch(Iterable<Product> entities) {

    }

    @Override
    public void deleteAllByIdInBatch(Iterable<Long> longs) {

    }

    @Override
    public void deleteAllInBatch() {

    }

    @Override
    public Product getOne(Long aLong) {
        return null;
    }

    @Override
    public Product getById(Long aLong) {
        return null;
    }

    @Override
    public Product getReferenceById(Long aLong) {
        return null;
    }

    @Override
    public <S extends Product> Optional<S> findOne(Example<S> example) {
        return Optional.empty();
    }

    @Override
    public <S extends Product> List<S> findAll(Example<S> example) {
        return null;
    }

    @Override
    public <S extends Product> List<S> findAll(Example<S> example, Sort sort) {
        return null;
    }

    @Override
    public <S extends Product> Page<S> findAll(Example<S> example, Pageable pageable) {
        return null;
    }

    @Override
    public <S extends Product> long count(Example<S> example) {
        return 0;
    }

    @Override
    public <S extends Product> boolean exists(Example<S> example) {
        return false;
    }

    @Override
    public <S extends Product, R> R findBy(Example<S> example, Function<FluentQuery.FetchableFluentQuery<S>, R> queryFunction) {
        return null;
    }

    @Override
    public <S extends Product> List<S> saveAll(Iterable<S> entities) {
        return null;
    }

    @Override
    public List<Product> findAll() {
        return null;
    }

    @Override
    public List<Product> findAllById(Iterable<Long> longs) {
        return null;
    }

    @Override
    public long count() {
        return 0;
    }

    @Override
    public void deleteById(Long aLong) {

    }

    @Override
    public void delete(Product entity) {

    }

    @Override
    public void deleteAllById(Iterable<? extends Long> longs) {

    }

    @Override
    public void deleteAll(Iterable<? extends Product> entities) {

    }

    @Override
    public void deleteAll() {

    }

    @Override
    public List<Product> findAll(Sort sort) {
        return null;
    }

    @Override
    public Page<Product> findAll(Pageable pageable) {
        return null;
    }
}
