package com.d201.fundingift.unit.mock;

import com.d201.fundingift.product.entity.Product;
import com.d201.fundingift.product.entity.ProductOption;
import com.d201.fundingift.product.repository.ProductOptionRepository;
import org.springframework.data.domain.*;
import org.springframework.data.repository.query.FluentQuery;

import java.util.ArrayList;
import java.util.List;
import java.util.Objects;
import java.util.Optional;
import java.util.function.Function;

public class FakeProductOptionRepository implements ProductOptionRepository {

    private Long autoGeneratedId = 0L;
    private final List<ProductOption> data = new ArrayList<>();

    @Override
    public Optional<ProductOption> findByIdAndStatusIsActive(Long id) {
        return data.stream().filter(item -> item.getId().equals(id)).findAny();
    }

    @Override
    public <S extends ProductOption> S save(S entity) {

        if(entity.getId() == null) {
            ProductOption newProductOption = ProductOption.builder()
                    .id(++autoGeneratedId)
                    .name(entity.getName())
                    .price(entity.getPrice())
                    .status(entity.getStatus())
                    .product(entity.getProduct())
                    .build();

            data.add(newProductOption);

            return (S) newProductOption;
        } else {
            data.removeIf(item -> Objects.equals(item.getId(), entity.getId()));
            data.add(entity);

            return entity;
        }
    }

    @Override
    public Optional<ProductOption> findByIdAndStatusIsNotInactive(Long productOptionId) {
        return Optional.empty();
    }

    @Override
    public List<ProductOption> findByProductAndStatusIsNotInactive(Product product) {
        return null;
    }

    @Override
    public void flush() {

    }

    @Override
    public <S extends ProductOption> S saveAndFlush(S entity) {
        return null;
    }

    @Override
    public <S extends ProductOption> List<S> saveAllAndFlush(Iterable<S> entities) {
        return null;
    }

    @Override
    public void deleteAllInBatch(Iterable<ProductOption> entities) {

    }

    @Override
    public void deleteAllByIdInBatch(Iterable<Long> longs) {

    }

    @Override
    public void deleteAllInBatch() {

    }

    @Override
    public ProductOption getOne(Long aLong) {
        return null;
    }

    @Override
    public ProductOption getById(Long aLong) {
        return null;
    }

    @Override
    public ProductOption getReferenceById(Long aLong) {
        return null;
    }

    @Override
    public <S extends ProductOption> Optional<S> findOne(Example<S> example) {
        return Optional.empty();
    }

    @Override
    public <S extends ProductOption> List<S> findAll(Example<S> example) {
        return null;
    }

    @Override
    public <S extends ProductOption> List<S> findAll(Example<S> example, Sort sort) {
        return null;
    }

    @Override
    public <S extends ProductOption> Page<S> findAll(Example<S> example, Pageable pageable) {
        return null;
    }

    @Override
    public <S extends ProductOption> long count(Example<S> example) {
        return 0;
    }

    @Override
    public <S extends ProductOption> boolean exists(Example<S> example) {
        return false;
    }

    @Override
    public <S extends ProductOption, R> R findBy(Example<S> example, Function<FluentQuery.FetchableFluentQuery<S>, R> queryFunction) {
        return null;
    }

    @Override
    public <S extends ProductOption> List<S> saveAll(Iterable<S> entities) {
        return null;
    }

    @Override
    public Optional<ProductOption> findById(Long aLong) {
        return Optional.empty();
    }

    @Override
    public boolean existsById(Long aLong) {
        return false;
    }

    @Override
    public List<ProductOption> findAll() {
        return null;
    }

    @Override
    public List<ProductOption> findAllById(Iterable<Long> longs) {
        return null;
    }

    @Override
    public long count() {
        return 0;
    }

    @Override
    public void deleteById(Long aLong) {

    }

    @Override
    public void delete(ProductOption entity) {

    }

    @Override
    public void deleteAllById(Iterable<? extends Long> longs) {

    }

    @Override
    public void deleteAll(Iterable<? extends ProductOption> entities) {

    }

    @Override
    public void deleteAll() {

    }

    @Override
    public List<ProductOption> findAll(Sort sort) {
        return null;
    }

    @Override
    public Page<ProductOption> findAll(Pageable pageable) {
        return null;
    }
}
