package com.d201.fundingift.unit.mock;

import com.d201.fundingift.funding.intrastructure.entity.AnniversaryCategory;
import com.d201.fundingift.funding.intrastructure.repository.AnniversaryCategoryRepository;
import org.springframework.data.domain.Example;
import org.springframework.data.domain.Page;
import org.springframework.data.domain.Pageable;
import org.springframework.data.domain.Sort;
import org.springframework.data.repository.query.FluentQuery;

import java.util.ArrayList;
import java.util.List;
import java.util.Objects;
import java.util.Optional;
import java.util.function.Function;

public class FakeAnniversaryCategoryRepository implements AnniversaryCategoryRepository {

    private Integer autoGeneratedId = 0;
    private final List<AnniversaryCategory> data = new ArrayList<>();

    @Override
    public Optional<AnniversaryCategory> findById(Integer id) {
        return data.stream().filter(item -> item.getId().equals(id)).findAny();
    }

    @Override
    public <S extends AnniversaryCategory> S save(S entity) {
        if(entity.getId() == null) {
            AnniversaryCategory newAnniversaryCategory = new AnniversaryCategory(++autoGeneratedId, entity.getName());

            data.add(newAnniversaryCategory);

            return (S) newAnniversaryCategory;
        } else {
            data.removeIf(item -> Objects.equals(item.getId(), entity.getId()));
            data.add(entity);

            return entity;
        }
    }

    @Override
    public void flush() {

    }

    @Override
    public <S extends AnniversaryCategory> S saveAndFlush(S entity) {
        return null;
    }

    @Override
    public <S extends AnniversaryCategory> List<S> saveAllAndFlush(Iterable<S> entities) {
        return null;
    }

    @Override
    public void deleteAllInBatch(Iterable<AnniversaryCategory> entities) {

    }

    @Override
    public void deleteAllByIdInBatch(Iterable<Integer> integers) {

    }

    @Override
    public void deleteAllInBatch() {

    }

    @Override
    public AnniversaryCategory getOne(Integer integer) {
        return null;
    }

    @Override
    public AnniversaryCategory getById(Integer integer) {
        return null;
    }

    @Override
    public AnniversaryCategory getReferenceById(Integer integer) {
        return null;
    }

    @Override
    public <S extends AnniversaryCategory> Optional<S> findOne(Example<S> example) {
        return Optional.empty();
    }

    @Override
    public <S extends AnniversaryCategory> List<S> findAll(Example<S> example) {
        return null;
    }

    @Override
    public <S extends AnniversaryCategory> List<S> findAll(Example<S> example, Sort sort) {
        return null;
    }

    @Override
    public <S extends AnniversaryCategory> Page<S> findAll(Example<S> example, Pageable pageable) {
        return null;
    }

    @Override
    public <S extends AnniversaryCategory> long count(Example<S> example) {
        return 0;
    }

    @Override
    public <S extends AnniversaryCategory> boolean exists(Example<S> example) {
        return false;
    }

    @Override
    public <S extends AnniversaryCategory, R> R findBy(Example<S> example, Function<FluentQuery.FetchableFluentQuery<S>, R> queryFunction) {
        return null;
    }
    @Override
    public <S extends AnniversaryCategory> List<S> saveAll(Iterable<S> entities) {
        return null;
    }

    @Override
    public boolean existsById(Integer integer) {
        return false;
    }

    @Override
    public List<AnniversaryCategory> findAll() {
        return null;
    }

    @Override
    public List<AnniversaryCategory> findAllById(Iterable<Integer> integers) {
        return null;
    }

    @Override
    public long count() {
        return 0;
    }

    @Override
    public void deleteById(Integer integer) {

    }

    @Override
    public void delete(AnniversaryCategory entity) {

    }

    @Override
    public void deleteAllById(Iterable<? extends Integer> integers) {

    }

    @Override
    public void deleteAll(Iterable<? extends AnniversaryCategory> entities) {

    }

    @Override
    public void deleteAll() {

    }

    @Override
    public List<AnniversaryCategory> findAll(Sort sort) {
        return null;
    }

    @Override
    public Page<AnniversaryCategory> findAll(Pageable pageable) {
        return null;
    }
}
