name: Deploy Spring Boot Application with Docker

on:
  push:
    branches:
      - "main"

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout the main branch (default)
      - name: Checkout Code
        uses: actions/checkout@v4

      # 2. Download application-secret.yml from GitHub Secrets
      - name: Download application-secret.yml
        env:
          SECRET_CONTENT: ${{ secrets.SECRET }}
        run: |
          echo "$SECRET_CONTENT" > ./src/main/resources/application-secret.yml

      # 3. Download fcm-certification.json from GitHub Secrets
      - name: Download fcm-certification.json
        env:
          FCM_CERT: ${{ secrets.FCM_SECRET }}
        run: |
          echo "$FCM_CERT" > ./src/main/resources/fcm-certification.json

      # 4. Build and run Docker container
      - name: Build and Run Docker Container
        run: |
          # Check if a container named 'be' is running
          RUNNING_CONTAINER=$(docker ps -a --filter "name=be" --format "{{.Names}}")

          if [ "$RUNNING_CONTAINER" ]; then
            echo "Stopping and removing the 'be' container..."
            docker stop be || true
            docker rm be || true
            docker rmi be || true
          fi

          echo "Building the Docker image..."
          docker build -t be .

          echo "Running the Docker container..."
          docker run -d --name be -p 8081:8081 be
